config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers, :messages_to, :messages_from
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:destroy]
  resources :relationships, only: [:create, :destroy]
  resources :parser, only: [:create]

  match '/signup',	to:	'users#new'
  match '/signin',	to:	'sessions#new'
  match '/signout',	to:	'sessions#destroy', via: :delete

  match '/contact',	to:	'static_pages#contact'
  match '/about',	to:	'static_pages#about'
  match '/help',	to:	'static_pages#help'

  root			to:	'static_pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.username, feed_item.user %>
  </span>
  <span class="content">
    <% if feed_item.is_reply_to? %>
      <%= link_to "@#{feed_item.in_reply_to.username}", feed_item.in_reply_to %>
      <%= wrap(feed_item.content.gsub(/\A^@\w+/, "")) %>
    <% else %>
      <%= wrap(feed_item.content) %>
    <% end %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago
    <% if feed_item.is_reply_to? %>
      in reply to <%= feed_item.in_reply_to.username %>.
    <% end %>
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
      data: { confirm: "You sure?" },
      title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  <h4>See the <%= link_to "Help", help_path %> for a list of added functionality.</h4>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_microposts.html.erb
<table class="front" summary="For signed-in users">
  <tr>
    <td class="main">
      <h1 class="micropost">What's up?</h1>
      <%= render 'shared/micropost_form' %>
      <%= render 'shared/feed' %>
    </td>
    <td class="sidebar round">
      <%= render 'shared/user_info' %>
      <%= render 'shared/stats' %>
    </td>
  </tr>
</table>

app/views/shared/_parser_form.html.erb
<%= form_tag '/parser' do %>
  <!--%= render 'shared/error_messages', :object => f.object %-->
  <div class="field">
    <%= text_area_tag 'command', params[:command], placeholder: 'Compose new micropost...' %>
  </div>
  <%= submit_tag "Submit", class: "btn btn-large btn-primary", name: nil %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.username %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>